bg_kin2_fence OK and documented
zeldaret/mm pull request #103
Opened 2021-04-10 00:51 UTC by kyleburnette

2021-04-19 21:47 UTC, Kenix3 requested changes

2021-04-19 21:47 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Fence/z_bg_kin2_fence.c
> +Vec3f D_80B6EE80[][2] = { { { -215.0f, 139.0f, 50.0f }, { -193.0f, 139.0f, 50.0f } },
Everything else is documented, would you like to come up with a name for this vector array?
Looks to me like it has to do with the spawn positions of the particles.

2021-05-01 20:48 UTC, jpburnett approved these changes
lgtm

2021-05-03 21:18 UTC, Kenix3 approved these changes
Looks good to me!

2021-05-03 21:19 UTC, merged