Obj_Lightswitch (incomplete)
zeldaret/mm pull request #107
Opened 2021-04-17 21:47 UTC by isghj5

Three non-equivelent functions:

The function that spawns burning flames for the fake light switches
The polyxlu draw function for the fake switches
The polyopa function for real switches

Both draw functions are nearly identical and have the same issue, but I couldn't figure out how to get them to match

2021-05-04 23:06 UTC, Kenix3 requested changes
Names are suggested, but the naming convention and format are what is expected. Thank you for the submission!

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_8096012C(ObjLightswitch* this) {
`ObjLightSwitch_SetupAsleep`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960148(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_Asleep`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960224(ObjLightswitch* this) {
`ObjLightSwitch_SetupEnabled`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960260(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_Enabled`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_8096034C(ObjLightswitch* this) {
`ObjLightSwitch_SetupDisabled`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960370(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_Disabled`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960424(ObjLightswitch* this) {
`ObjLightSwitch_SetupFade`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960440(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_Fade`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_80960880(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_DrawXlu`

2021-05-04 23:06 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void func_809605F4(ObjLightswitch* this, GlobalContext* globalCtx) {
`ObjLightSwitch_DrawOpa`

2021-05-05 05:17 UTC, isghj5 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void* D_80960BC4[] = { 0x06000C20, 0x06000420, 0x06001420,}; // D_80960BC4
These are going to be parts of the object right? gfx pointers?

Can I wait until we can decomp objects? There was a discussion about those being required at some point right?

2021-05-05 20:15 UTC, isghj5 commented
Hmm, I started implemented requested changes and now its giving a weird error on make (regular/clean and init)
```
cp: -r not specified; omitting directory 'baserom/assets'
make: *** [Makefile:200: build/baserom/assets] Error 1
```

2021-05-05 21:41 UTC, isghj5 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +Color_RGBA8 D_80960BD0 = { 0xFF, 0xFF, 0xA0, 0xA0, };
I don't know how to rename these currently, as they are used in the non-matching polyopa/polyxlu functions the asm is looking for the old values. Do I have to re-enable asm data in code_script.txt?

2021-05-06 22:19 UTC, Kenix3 commented on src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
> +void* D_80960BC4[] = { 0x06000C20, 0x06000420, 0x06001420,}; // D_80960BC4
I would like to see symbols for all known addresses. I've been requiring all syms for assets, even in arrays.

Object decomp is when names for the display lists etc will be required. :) We are still waiting a bit for Tharo to be done with his semester at school to see if we can automate object decomp.

Should also add that the type for this looks to be `Gfx*`

2021-05-06 22:19 UTC, Kenix3 requested changes
Sorry again, but I noticed a few more things.

2021-05-10 02:18 UTC, Kenix3 approved these changes
Looks good to me, this is ready to merge.

2021-05-10 02:18 UTC, merged