Ovl_En_Cha OK
zeldaret/mm pull request #116
Opened 2021-04-27 07:35 UTC by hensldm

2021-04-28 00:11 UTC, jpburnett reviewed
Looks good, just a couple thoughts:
1. see the suggestion on the return statements
2. It could just be me, and others can chime in, I like having a description up top to know what actor I am looking at since the names aren't always indicative. ex: 
```
/*
 * File: z_en_cha.c
 * Overlay: ovl_En_Cha
 * Description: Laundry Pool Bell
 */
 ```

2021-04-28 00:11 UTC, jpburnett commented on src/overlays/actors/ovl_En_Cha/z_en_cha.c
> +    ActorCutscene_SetIntentToPlay(this->actor.cutscene);
```suggestion
    if (this->actor.cutscene == -1) {
        this->actionFunc = func_80BEB654;
    }
    else if (ActorCutscene_GetCanPlayNext(this->actor.cutscene)) {
        ActorCutscene_StartAndSetUnkLinkFields(this->actor.cutscene, &this->actor);
        this->actionFunc = func_80BEB654;
    } else {
        ActorCutscene_SetIntentToPlay(this->actor.cutscene);
    }
```
Just out of curiosity, does this work to get rid of the returns?

2021-05-01 16:39 UTC, Kenix3 requested changes

2021-05-01 16:39 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Cha/z_en_cha.c
> +void func_80BEB654(EnCha *this, GlobalContext *globalCtx) {
This looks to be the bell's idle function.
Can you please rename this to something like
`EnCha_Idle`

2021-05-01 16:39 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Cha/z_en_cha.c
> +void func_80BEB5DC(EnCha *this, GlobalContext *globalCtx) {
This looks to be the action state that handles the cutscene that brings out Kaffei.
Can you please rename this to something like
`EnCha_Ring`

2021-05-01 17:12 UTC, jpburnett approved these changes
looks clean 👍

2021-05-05 00:04 UTC, Kenix3 approved these changes
Looks good to me!

2021-05-05 00:10 UTC, merged