code_0x8017FEB0 OK
zeldaret/mm pull request #137
Opened 2021-05-14 17:09 UTC by AngheloAlf

I'm a bit unsure about `D_801E01E0`. It seems to be used only by `atan`. I don't know how to import that variable to code.

I also fixed the signature of `atan_flip`.

2021-05-14 20:24 UTC, AngheloAlf commented
This is fixed now!

2021-05-15 16:10 UTC, hensldm approved these changes
Looks good to me. Only saw one small thing.

2021-05-15 16:10 UTC, hensldm commented on src/code/code_0x8017FEB0.c
> +    s32 phi_v1;
`angle` seems like a better name then `phi_v1`.

2021-05-16 04:22 UTC, Zelllll requested changes
If these functions exist in oot they should probably be using the same names, and everything should be camelCase. Also the `atan_first_8th_array` should be `static u16 sAtanFirstEighth[]` or something instead

2021-05-16 15:18 UTC, AngheloAlf commented
The equivalent file seems to be [sys_math_atan.c](https://github.com/zeldaret/oot/blob/master/src/code/sys_math_atan.c), so I'll rename the functions and the filename too

2021-05-16 16:26 UTC, AngheloAlf commented
Update: 
- I renamed the functions and the file to match its OoT counterpart.
- I also added the renamed functions to `actorfixer.py`

2021-05-16 16:30 UTC, Zelllll approved these changes
Looks good now

2021-05-19 02:50 UTC, Kenix3 approved these changes
Looks great to me! Don't forget to run format.sh on this.

2021-05-19 02:58 UTC, merged