Ovl_Bg_Ctower_Rot Ok
zeldaret/mm pull request #149
Opened 2021-05-18 22:16 UTC by hensldm

Ovl_Bg_Ctower_Rot take 2.

2021-05-18 23:07 UTC, AngheloAlf reviewed
Good job, just a minor comment

2021-05-19 03:01 UTC, Kenix3 requested changes
One small variable left to name, otherwise it looks good.
Don't forget to run format.sh on this now that the repo can be formatted!

2021-05-19 03:01 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ctower_Rot/z_bg_ctower_rot.c
> +static Gfx* D_808E2564[] = { D_06012DA0, D_06017220, D_060174E0 };
`bgCtowerRotDlists`

2021-05-19 03:27 UTC, hensldm commented on src/overlays/actors/ovl_Bg_Ctower_Rot/z_bg_ctower_rot.c
> +static Gfx* D_808E2564[] = { D_06012DA0, D_06017220, D_060174E0 };
👍

2021-05-20 02:33 UTC, Kenix3 approved these changes

2021-05-20 21:23 UTC, merged