Apply the NORETURN attribute to functions that do not return
zeldaret/mm pull request #1768
Opened 2024-12-17 22:21 UTC by Thar0

Some rationale in the corresponding OoT PR
https://github.com/zeldaret/oot/pull/1532

2024-12-18 06:16 UTC, engineer124 approved these changes

2024-12-18 17:15 UTC, hensldm approved these changes

2024-12-18 21:09 UTC, AngheloAlf requested changes

2024-12-18 21:09 UTC, AngheloAlf commented on src/boot/fault.c
> +NORETURN void Fault_AddHungupAndCrash(const char* file, s32 line) {
I think `_dbg_hungup` and `Reset` from `debug.c` should have the `NORETURN` attribute since they unconditionally call `Fault_AddHungupAndCrash` too

2024-12-22 21:51 UTC, AngheloAlf approved these changes

2024-12-22 23:24 UTC, merged