bg_market_step OK
zeldaret/mm pull request #21
Opened 2020-09-20 07:41 UTC by fullgrowngaming

2020-09-21 03:22 UTC, Rozelette approved these changes
LGTM

2020-09-23 23:57 UTC, Kenix3 requested changes

2020-09-23 23:57 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Market_Step/z_bg_market_step.c
> +s32 D_80AF0120[] = { 0x0601F050, 0x06018DA0 };
This is really an array of pointers to to some object file data.
Can you try to determine the type? Likely Gfx*
The pointers should be defined in undefined syms.

2020-09-23 23:57 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Market_Step/z_bg_market_step.c
> +s32 D_80AF0128[] = { 0x0601EF10, 0x06018C60 };
This is really an array of pointers to to some object file data.
Can you try to determine the type? Likely Gfx*
The pointers should be defined in undefined syms.

2020-09-28 23:22 UTC, Kenix3 approved these changes

2020-09-28 23:26 UTC, merged