z_construct OK
zeldaret/mm pull request #267
Opened 2021-08-09 00:31 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

I don't love the name, I'd quite like to change it to `func_`. On the other hand, smallest PR to OK something is nice...

2021-08-10 04:05 UTC, AngheloAlf requested changes

2021-08-10 04:05 UTC, AngheloAlf commented on src/code/z_construct.c
> +void nop_801AAAA0(GlobalContext* globalCtx) {
```suggestion
void func_801AAAA0(GlobalContext* globalCtx) {
```

2021-08-13 04:20 UTC, AngheloAlf approved these changes

2021-08-13 04:22 UTC, engineer124 approved these changes

2021-08-14 22:49 UTC, isghj5 approved these changes

2021-08-18 12:51 UTC, Kenix3 approved these changes

2021-08-18 15:24 UTC, merged