en_tanron6 OK
zeldaret/mm pull request #27
Opened 2020-09-23 01:47 UTC by fullgrowngaming

2020-09-23 01:50 UTC, Rozelette approved these changes
LGTM

2020-09-23 23:50 UTC, Kenix3 requested changes

2020-09-23 23:50 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Tanron6/z_en_tanron6.c
> +void EnTanron6_SetupDoNothing(EnTanron6* this) {
Not a fan of this function name. EnTanron6_SetupActionFunc is better.

2020-09-23 23:55 UTC, fullgrowngaming commented
I had it that originally, but the OoT people told me that was only used in cases where an actionfunc was actually passed into the "setupaction" function, and otherwise, it's named along these lines

2020-09-24 00:08 UTC, Kenix3 commented
> 
> 
> I had it that originally, but the OoT people told me that was only used in cases where an actionfunc was actually passed into the "setupaction" function, and otherwise, it's named along these lines

It doesn't DoNothing, so the name is very bad. If the naming comes from the OOT people, then we need to have a conversation with them.

If there's no better name, then it should be named back to "func_80BE60BC" for now.

2020-09-24 00:18 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Tanron6/z_en_tanron6.c
> +void EnTanron6_SetupDoNothing(EnTanron6* this) {
I made a mistake here. This doesn't accept a function pointer. It just sets a statically defined function to the actionFunc.

2020-09-24 00:20 UTC, Kenix3 requested changes
I made a mistake in the initial review. I thought the actionFunc was being set to a function pointer argument rather than a statically defined function.

I do still think it's unclear that it sets up the "DoNothing" action, so I would suggest to name the "DoNothing" function at the same time.

2020-09-24 00:20 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Tanron6/z_en_tanron6.c
> +void func_80BE60D0(EnTanron6* this, GlobalContext* globalCtx);
This should be named EnTanron6_DoNothing

2020-09-28 23:27 UTC, Kenix3 approved these changes

2020-09-28 23:27 UTC, merged