En_Pm
zeldaret/mm pull request #309
Opened 2021-09-11 03:51 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2021-09-17 23:11 UTC, tom-overton commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> + * Description:
Looking at it in kz, it seems like this actor is the Postman:

![NKZJ01_2021-09-17_16-08-27](https://user-images.githubusercontent.com/12245827/133862518-8aa5fcb0-2fb7-4644-b566-962008979e08.png)

```suggestion
 * Description: Postman
```

2021-09-24 08:41 UTC, engineer124 reviewed
Great work with this! Only some very minor comments

2021-09-24 08:41 UTC, engineer124 commented on include/functions.h
> +Actor* func_8013A7C0(GlobalContext* globalCtx, s32 arg0);
```suggestion
Actor* func_8013A7C0(GlobalContext* globalCtx, s32 arg1);
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +    s32 ret = 0;
```suggestion
    s32 ret = false;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +            ret = 1;
```suggestion
            ret = true;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +    s32 ret = 0;
```suggestion
    s32 ret = false;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +    s32 ret = 0;
```suggestion
    s32 ret = false;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +        ret = 1;
```suggestion
        ret = true;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +    s32 ret = 0;
```suggestion
    s32 ret = false;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +        ret = 1;
```suggestion
        ret = true;
```

2021-09-24 08:41 UTC, engineer124 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.c
> +        ret = 1;
```suggestion
    s32 ret = false;

    if (func_80AF8ED4(this, globalCtx, arg2, ACTORCAT_NPC, ACTOR_EN_AN)) {
        func_8013AED4(&this->unk_356, 3, 7);
        this->unk_356 |= 0x20;
        this->unk_356 |= 0x9000;
        if (this->unk_258 != 0) {
            this->unk_356 |= 0x800;
            func_80AF7E98(this, 5);
        } else {
            func_80AF7E98(this, 3);
        }
        ret = true;
```

2021-09-26 04:16 UTC, engineer124 approved these changes

2021-09-28 00:17 UTC, Kenix3 requested changes

2021-09-28 00:17 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.h
> +    /* 0x0390 */ char unk390[0x4];
```suggestion
    /* 0x0390 */ UNK_TYPE1 unk390[0x4];
```

2021-09-28 00:17 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Pm/z_en_pm.h
> +    /* 0x039C */ char unk39C[0x4];
```suggestion
    /* 0x039C */ UNK_TYPE1 unk39C[0x4];
```

2021-11-03 17:18 UTC, AngheloAlf approved these changes
Looks good. Don't forget to address the other reviews and to fix conflicts

2021-11-04 17:23 UTC, hensldm requested changes

2021-11-04 17:23 UTC, hensldm commented on src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
> +    f32 sp7C[256];
```suggestion
    f32 sp7C[265];
```
Should be the same as En_Pm

2021-11-11 04:12 UTC, Kenix3 approved these changes

2021-11-12 01:41 UTC, merged