Main OK
zeldaret/mm pull request #329
Opened 2021-09-22 23:51 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

The most important function in the game!

After I realised the sizeof thing, this wasn't too bad. The weirdest thing is the regalloc around the heap stuff, which required `s32`s and a temp to get the regalloc to work out. I named the temp the same as the one OoT uses for the end of the system heap, but there's probably a better one.

This one's a bit different from the OoT one, but shares most of the Init stuff. And being MM, of course it has a switch in it...

2021-09-22 23:54 UTC, AngheloAlf approved these changes

2021-09-24 11:18 UTC, engineer124 approved these changes
Pretty cool. I can only really comment on styling, and styling lgtm

2021-09-24 13:18 UTC, Thar0 requested changes

2021-09-24 13:18 UTC, Thar0 commented on src/code/main.c
> +    osSetEventMesg(5, &siEventCallbackQueue, NULL);
```suggestion
    osSetEventMesg(OS_EVENT_SI, &siEventCallbackQueue, NULL);
```

2021-09-25 00:27 UTC, Thar0 approved these changes

2021-09-29 22:26 UTC, Kenix3 approved these changes

2021-09-29 22:27 UTC, merged