Adding tools.md
zeldaret/mm pull request #344
Opened 2021-10-03 03:48 UTC by jpburnett

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

Getting back in to the swing of things I thought I would refresh myself on some of the tools. I filled in what I could / what I knew about the tools. This is also an effort to close #144 to clean things up. Feel free to let me know what is missing. This isn't a high priority to get it.

2021-11-03 15:02 UTC, AngheloAlf reviewed
Looks good overall.
I think extract_assets.py and graphovl.py are missing tho

2021-11-03 22:30 UTC, Kenix3 reviewed
This PR is also probably a good place to explain how to use the google sheet reservation board.

2021-11-03 22:35 UTC, jpburnett commented on docs/tools.md
> +There are different ways you can run mpips2c:
Sounds good, I can add a section on that

2021-12-01 01:26 UTC, EllipticEllipsis commented on docs/tools.md
> +We use a [Google Sheet](https://docs.google.com/spreadsheets/d/1X83YCPRa532v-Zo0WgUsJ2kB1X9RxBta5_p9aWA8uro/edit#gid=0>) to keep track of all the files worked on and their merge status. On this board
Probably mention what "interested" means too.

2021-12-01 01:34 UTC, hensldm requested changes

2021-12-01 01:34 UTC, hensldm commented on docs/tools.md
> +(Exists in a subrepo.)
This is no longer true, should just remove it.

2021-12-01 03:35 UTC, AngheloAlf approved these changes

2021-12-10 11:35 UTC, EllipticEllipsis reviewed
I'm happy apart from the sheet description: I've rewritten the paragraph into some explicit column-describing bullet points, see what you think.

2021-12-10 11:35 UTC, EllipticEllipsis commented on docs/tools.md
> +We use a [Google Sheet](https://docs.google.com/spreadsheets/d/1X83YCPRa532v-Zo0WgUsJ2kB1X9RxBta5_p9aWA8uro/edit#gid=0>) to keep track of all the files worked on and their merge status. On this board
```suggestion
We use a [Google Sheet](https://docs.google.com/spreadsheets/d/1X83YCPRa532v-Zo0WgUsJ2kB1X9RxBta5_p9aWA8uro/edit#gid=0) to keep track of all the files' decompilation statuses and their function statistics. On this board one can reserve a file to work on. The columns are

- **Actor Id**: The enum that uniquely identifies the actor for spawning etc., useful for looking in KZ/VerboseOcarina/Spectrum. For `boot`/`code`, the VRAM of the file's .text start is given instead.
- **Overlay/File name**: Hopefully obvious, although some remain unknown.
- **Function size statistics**: Intended as a crude estimate of how hard a file will be. Beginners should look for small largest function size and total size; the columns give a rough estimate of the distribution of function sizes without getting unnecessarily statistically descriptive. As you become more experienced, you should work on larger files to 
- **Description**: What the file is. It's helpful if you can fill this in if you know! They should be synchronised with the short top-of-file descriptions.
- **Status**: (Free)/Reserved/PR/Merged. To be kept up-to-date by the reserver.
- **Reserved**: To reserve a file, put your Discord name in the "Reserved" column. It is common courtesy to not work on a file that is being worked on by another contributor, so ensure the "Reserved" column is blank before working on a file. If it is not, you can ask the reserver(s) if they want to release it or collaborate on it, but don't expect them to agree. More information on what is expected when you reserve a file is available in the [CONTRIBUTING.md](../CONTRIBUTING.md).
- **Interested**: If you would like to work on a file, but don't want to reserve it, or would be interested in collaboration, etc. You should talk to any Interested people if you want to work on the file.
- **Notes**: Any other useful information: partial progress by someone unable to finish the file, other files it works with, etc.
```

2021-12-10 22:27 UTC, hensldm approved these changes

2021-12-11 22:29 UTC, EllipticEllipsis commented on docs/tools.md
> +- **Function size statistics**: Intended as a crude estimate of how hard a file will be. Beginners should look for small largest function size and total size; the columns give a rough estimate of the
```suggestion
- **Function size statistics**: Intended as a crude estimate of how hard a file will be. Beginners should look for small largest function size and total size; the columns give a rough estimate of the distribution of function sizes without getting unnecessarily statistically descriptive. As you become more experienced, you should work on larger files to leave the smaller ones for other beginners.
```

Ah, apparently this sentence didn't finish itself?

2021-12-16 04:06 UTC, Kenix3 approved these changes

2021-12-16 04:56 UTC, merged