en_dy_extra OK
zeldaret/mm pull request #35
Opened 2020-10-12 19:11 UTC by fullgrowngaming

2020-10-12 20:17 UTC, m4xw requested changes

2020-10-12 20:17 UTC, m4xw commented on src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
> +    if (this->actor.currPosRot.pos.y < -85.0f) {
\n

2020-10-12 20:17 UTC, m4xw commented on src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
> +    if (this->unk14C == 0 && this->unk14A != 0) {
\n before as above

2020-10-12 20:17 UTC, m4xw commented on src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
> +    this->unk150 -= 0.02f;
\n before this

2020-10-12 20:17 UTC, m4xw commented on src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
> +    if (this->unk14C == 0 || this->unk150 < 0.02f) {
\n before this

2020-10-12 20:17 UTC, m4xw commented on include/color.h
> +} Color_RGBA8_n;
as discussed

2020-10-12 20:18 UTC, m4xw commented on src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
> +    if (this->actor.currPosRot.pos.y < -85.0f) {
(before this)

2020-10-12 21:23 UTC, Kenix3 approved these changes
Looks good to me.
Build is OK.

2020-10-12 23:08 UTC, fullgrowngaming commented
Fixed the unnecessary color thing, but I'm a bit confused about the newline suggestions

2020-10-12 23:18 UTC, fig02 commented
I prefer separating out blocks myself like m4 suggested, but it might be a bit cumbersome to enforce project wide. at least in oot we dont enforce anything related to that, dunno if mm agreed on a style for that tho

2020-10-12 23:32 UTC, fullgrowngaming commented
(went ahead and added the newlines, but yeah, we should probably discuss whether that's something to enforce at this stage)

2020-10-13 03:24 UTC, Rozelette approved these changes
LGTM

2020-10-13 03:30 UTC, merged