Obj_Iceblock
zeldaret/mm pull request #367
Opened 2021-10-19 11:30 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2021-11-02 19:56 UTC, Kenix3 requested changes

2021-11-02 19:56 UTC, Kenix3 commented on include/variables.h
> +
+1 to this

2021-11-30 15:47 UTC, AngheloAlf commented on include/functions.h
> +void FlagSet_Update(GameState* gamestate);
```suggestion
void FlagSet_Update(GameState* gameState);
```

2021-11-30 15:47 UTC, AngheloAlf commented on src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
> +        D_80A26E7C = (AnimatedMaterial*)Lib_SegmentedToVirtual(&D_06000328);
I think there's no need for this cast
```suggestion
        D_80A26E7C = Lib_SegmentedToVirtual(&D_06000328);
```

2021-11-30 15:47 UTC, AngheloAlf commented on src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
> +    Math_StepToF(&this->unk_2A8, (1.0f / 600.0f), 0.00016666666f);
Would this match?
```suggestion
    Math_StepToF(&this->unk_2A8, (1.0f / 600.0f), (1.0f / 6000.0f));
```

2021-12-12 01:47 UTC, hensldm reviewed
A few formatting questions.

2021-12-12 01:47 UTC, hensldm commented on src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
> +    };
Same here, does removing the trailing `,`s result in single lines?

2021-12-12 01:47 UTC, hensldm commented on src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
> +    static f32 D_80A26FC0[] = {
Same question here.

2021-12-21 15:24 UTC, AngheloAlf approved these changes

2021-12-21 16:44 UTC, hensldm approved these changes

2021-12-22 18:23 UTC, hensldm requested changes
With the object now, don't forget to remove the symbols from `undefined_syms.txt`.

2021-12-23 00:12 UTC, hensldm approved these changes

2021-12-27 00:07 UTC, Kenix3 approved these changes

2021-12-27 01:40 UTC, merged