En_Elf
zeldaret/mm pull request #371
Opened 2021-10-20 18:40 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

Documentation is from OoT.

2021-11-14 05:49 UTC, engineer124 reviewed
Nice work. Just a few small comments

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +            if ((gSaveContext.naviTimer >= 0x64C8) || (gSaveContext.naviTimer < 0xBB8)) {
```suggestion
            if ((gSaveContext.naviTimer >= 25800) || (gSaveContext.naviTimer < 3000)) {
```
These timers can be in dec

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +    xVelTarget = fabsf(xVelTarget);
```suggestion
    f32 zVelTarget = ((targetPos->z + this->unk_224.z) - this->actor.world.pos.z) * arg2;
    f32 xVelDirection = (xVelTarget >= 0.0f) ? 1.0f : -1.0f;
    f32 zVelDirection = (zVelTarget >= 0.0f) ? 1.0f : -1.0f;

    xVelTarget = fabsf(xVelTarget);
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +    this->unk_246 += this->unk_24A;
```suggestion
    f32 yVelTarget = (((Math_SinS(this->unk_246) * this->unk_250) + arg1->y) - this->actor.world.pos.y) * 0.2f;
    f32 yVelAbs = fabsf(yVelTarget);
    f32 yVelDirection = (yVelTarget >= 0.0f) ? 1.0f : -1.0f;

    this->unk_246 += this->unk_24A;
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +        this->unk_24A = (s32)Rand_ZeroFloat(1024.0f) + 0x200;
```suggestion
        this->unk_24A = (s32)Rand_ZeroFloat(0x400) + 0x200;
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +        }
```suggestion
        u16 targetSfxId = this->unk_269 == 0 ? NA_SE_PL_WALK_GROUND - SFX_FLAG : NA_SE_PL_WALK_GROUND - SFX_FLAG;

        if (!temp) {
            Audio_PlayActorSound2(&this->actor, targetSfxId);
        }
```
`SfxId` is the name we use for sound effects

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +                                } else if ((gSaveContext.time < 0x4000) && (gSaveContext.weekEventReg[74] & 0x20)) {
```suggestion
                                } else if ((gSaveContext.time < CLOCK_TIME(6, 0)) && (gSaveContext.weekEventReg[74] & 0x20)) {
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +        if ((gSaveContext.naviTimer >= 0x258) && (gSaveContext.naviTimer < 0xBB9)) {
```suggestion
        if ((gSaveContext.naviTimer >= 600) && (gSaveContext.naviTimer <= 3000)) {
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +        func_8019FDC8(&D_801DB4A4, 0x6873, 0x20);
```suggestion
        func_8019FDC8(&D_801DB4A4, NA_SE_VO_NA_LISTEN, 0x20);
```

2021-11-14 05:49 UTC, engineer124 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +}
Could you get this to match with the `VEC3F_LERPIMPDST` macro?

2021-11-30 16:11 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +            envAlpha = (this->timer * 50) & 0x1FF;
Would this match?
```suggestion
            envAlpha = (this->timer * 50) % 512;
```

2021-12-12 02:05 UTC, hensldm requested changes
A few things I noticed.

2021-12-12 02:05 UTC, hensldm commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +                    case 580:
These cases look like textIds so should probably be in hex.

2021-12-12 02:05 UTC, hensldm commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +        gSaveContext.naviTimer = 0;
I know this wasn't you, but this should be changed to tatlTimer.

2021-12-21 08:02 UTC, Kelebek1 commented on src/overlays/actors/ovl_En_Elf/z_en_elf.c
> +            envAlpha = (this->timer * 50) & 0x1FF;
Doesn't work due to being signed.

2021-12-21 15:53 UTC, AngheloAlf approved these changes

2021-12-21 16:42 UTC, hensldm approved these changes

2021-12-27 00:10 UTC, Kenix3 approved these changes

2021-12-27 01:47 UTC, merged