CRC files OK and documented
zeldaret/mm pull request #409
Opened 2021-11-04 03:52 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

Transferred the libultra `crc.c` functions from OoT. I spent a couple of days learning about CRC, and wrote what I hope are fairly comprehensive/comprehensible notes on how it works and how it is implemented in libultra.

Also included @engineer124 's work on `voicecrc.c`, since it is almost identical to the second function in `crc.c`; it is used by the other voice functions, but requires no specialised structs or anything, so we decided it fit better in this PR.

I didn't know what to do with the following note that the OoT file had, so I have left it in for the time being:
```
// Valid addr up to 0x7FF
// It's the address of a block of 0x20 bytes in the mempak
// So that means the whole mempak has a 16-bit address space
```

Finally, this doesn't really fit here, but is not worth a PR by itself: I made a small change to calc_bss.py so that it can be used from the project root with tab-completion; I also chmodded it to be executable.

2021-11-04 12:49 UTC, Thar0 requested changes
Looks good, I personally enjoyed the depth in the description of CRCs. Just some small things.

2021-11-04 12:49 UTC, Thar0 commented on src/libultra/voice/voicecrc.c
> +    for (byte = numBytes; byte; byte--, data++) {
Is this `!= 0`?
```suggestion
    for (byte = numBytes; byte != 0; byte--, data++) {
```
We usually don't drop comparisons like this.

2021-11-04 12:49 UTC, Thar0 commented on src/libultra/io/crc.c
> +    /* ret is used as a shift register for the CRC */
We usually use `//` for comments inside function bodies

2021-11-04 12:49 UTC, Thar0 commented on src/libultra/io/crc.c
> + */
imo the oot docs should just be included for now, suggestion below, and revised later if a more appropriate location for them crops up.
```suggestion
/**
 * CRC-5 with the generating polynomial $x^5 + x^4 + x^2 + 1 $, AKA 0x15 = 0b(1)1 0101.
 * It only works on the bits from 0x7FF = 11 11111111, i.e. 10 bits.
 *
 * Usually used as __osContAddressCrc(addr) | (addr << 5) to add the CRC to the end. The overall length of 10 + 5 bits
 * allows the address + CRC to fit into one s16.
 *
 * `addr` is the address of a block in the mempak, only valid up to 0x7FF.
 */
```

2021-11-05 00:35 UTC, AngheloAlf commented on src/libultra/io/crc.c
> +    for (bit = (1 << ADDRESS_CRC_MESSAGE_LENGTH); bit; bit >>= 1) {
```suggestion
    for (bit = (1 << ADDRESS_CRC_MESSAGE_LENGTH); bit != 0; bit >>= 1) {
```

2021-11-05 00:35 UTC, AngheloAlf commented on src/libultra/voice/voicecrc.c
> +        for (bit = (1 << (VOICE_CRC_LENGTH - 1)); bit; bit >>= 1) {
```suggestion
        for (bit = (1 << (VOICE_CRC_LENGTH - 1)); bit != 0; bit >>= 1) {
```

2021-11-05 12:47 UTC, Kenix3 requested changes
Great job on this!

2021-11-05 12:47 UTC, Kenix3 commented on src/libultra/voice/voicecrc.c
> +u8 __osVoiceContDataCrc(u8* data, u32 numBytes) {
```suggestion
u8 __osVoiceContDataCrc(u8* data, size_t numBytes) {
```

Is it possible to use size_t here? May not match.

2021-11-10 16:13 UTC, AngheloAlf approved these changes

2021-11-11 04:05 UTC, Kenix3 approved these changes

2021-11-11 16:42 UTC, hensldm approved these changes

2021-11-11 18:03 UTC, merged