epiread.c OK
zeldaret/mm pull request #410
Opened 2021-11-04 05:12 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

Are we using uintptr in libultra? It's not like these functions are exactly portable anyway.

2021-11-04 12:50 UTC, Thar0 approved these changes

2021-11-04 14:25 UTC, jpburnett approved these changes

2021-11-04 14:26 UTC, AngheloAlf approved these changes

2021-11-05 11:56 UTC, Kenix3 commented
> Before opening this PR, ensure the following:
> 
>     * `./format.sh` was run to apply standard formatting.
> 
>     * `make` successfully builds a matching ROM.
> 
>     * No new compiler warnings were introduced during the build process.
>       
>       * Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
> 
>     * New variables & functions should follow standard naming conventions.
> 
>     * Comments and variables have correct spelling.
> 
> 
> Are we using uintptr in libultra? It's not like these functions are exactly portable anyway.

Yes, we want to use uintptr_t whenever an address or offset is in question. Its just the correct type for the job.

2021-11-05 11:56 UTC, Kenix3 requested changes

2021-11-05 11:56 UTC, Kenix3 commented on src/libultra/io/epiread.c
> +s32 osEPiReadIo(OSPiHandle* handle, u32 devAddr, u32* data) {
```suggestion
s32 osEPiReadIo(OSPiHandle* handle, uintptr_t devAddr, u32* data) {
```

2021-11-11 04:04 UTC, Kenix3 approved these changes

2021-11-11 22:27 UTC, merged