En_Horse (3 non-matching)
zeldaret/mm pull request #413
Opened 2021-11-04 06:56 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

A bunch of things added and changed and removed here. Decomped this all normally and copied OoT names afterwards. 

The action/anim/flags enums are definitely wrong and will need to be changed, but I added the enums in anyways so it'll be easier to replace fix them all later when you get the right names, instead of leaving them as raw numbers which makes that harder. It looks like the enums shift by 2 somewhere I think, due to the new additions no doubt.

2021-11-19 14:58 UTC, Kenix3 approved these changes
Merge pending Anghelo and +1 contributor approval.

2021-11-20 03:16 UTC, jpburnett approved these changes
instead of saying neigh, I will say yay! good work on this

2021-11-20 06:07 UTC, engineer124 reviewed
Great work with this large actor! A few comments

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    }
```suggestion
    *stickMag = CLAMP_MAX(*stickMag, 60.0f);
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    s32 playSound;
```suggestion
    s32 playSfx;
```
Could you rename this?

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    if (s > 0.8660254f) { // sin(60 degrees)
```suggestion
    Player* player = GET_PLAYER(globalCtx);
    s16 angle = Actor_YawBetweenActors(&this->actor, &player->actor) - this->actor.world.rot.y;
    f32 s = Math_SinS(angle);
    f32 c = Math_CosS(angle);

    if (s > 0.8660254f) { // sin(60 degrees)
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +                   (Rand_ZeroOne() < (1.0f - ((curFrame - 6.0f) * 0.05882353f)))) {
```suggestion
                   (Rand_ZeroOne() < (1.0f - ((curFrame - 6.0f) * (1.0f / 17.0f))))) {
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    };
```suggestion
    static u8 D_80889210[] = {
        0,
        1,
        2,
        1
    };
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.h
> +    /* 0x224 */ char unk224[0xC];
```suggestion
    /* 0x224 */ UNK_TYPE1 unk224[0xC];     
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.h
> +    /* 0x374 */ char unk374[0x2];
```suggestion
    /* 0x374 */ UNK_TYPE1 unk374[0x2];      
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.h
> +    /* 0x390 */ char unk390[0x4];
```suggestion
    /* 0x390 */ UNK_TYPE1 unk390[0x4];      
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.h
> +    /* 0x3E4 */ char unk3E4[0x4];
```suggestion
    /* 0x3E4 */ UNK_TYPE1 unk3E4[0x4];      
```

2021-11-20 06:07 UTC, engineer124 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.h
> +    /* 0x588 */ char unk588[0x4];
```suggestion
    /* 0x54C */ UNK_TYPE1 unk54C[0x4];      
    /* 0x550 */ s32 unk_550;      
    /* 0x554 */ UNK_TYPE1 unk554[0x18];      
    /* 0x56C */ f32 unk_56C;             
    /* 0x570 */ Vec3f unk_570;             
    /* 0x57C */ Vec3f unk_57C;             
    /* 0x588 */ UNK_TYPE1 unk588[0x4];             
```

2021-12-27 00:14 UTC, Kenix3 requested changes
Please address review comments from engineer and fix merge conflicts.

Why is this currently a draft PR?

2021-12-27 00:15 UTC, AngheloAlf commented
It is waiting on #415

2021-12-27 19:37 UTC, Kelebek1 commented on include/functions.h
> +s32 Actor_NotMounted(GlobalContext* globalCtx, Actor* actor);
This is m2c's fault due to adding pointless comments to all this stuff, I asked for it to be removed but they declined. zbanks very recently added an option to turn off comments entirely though so it's not an issue anymore.

2021-12-27 19:39 UTC, Kelebek1 commented
Sorry i forgot to add that it was waiting, I'll put that in the description.

2022-01-04 00:05 UTC, Kenix3 approved these changes

2022-03-25 04:41 UTC, Kelebek1 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    sp64 = 9.99999968029e+37;
Unfortunately not.

2022-03-25 04:46 UTC, Kelebek1 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +            label:;
Yeah that fixes it.

2022-03-25 04:50 UTC, Kelebek1 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    turn = stickAngle * temp_f12 * temp_f12 * (2.2f - (this->actor.speedXZ * (1.0f / this->boostSpeed)));
Nope, not equiv since floats aren't associative.

2022-03-25 04:53 UTC, Kelebek1 commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +    } else {
Some have to skip all the code below. I can't see it being equivalent, but I tried it and it doesn't work.

2022-03-25 05:58 UTC, hensldm requested changes
Just clean up of undefined_syms

2022-03-25 05:58 UTC, hensldm commented on undefined_syms.txt
>  // ovl_En_Horse
Should be able to remove this section

2022-03-25 19:59 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +                func_80138258(&this->actor, globalCtx, &this->skin, EnHorse_SkinCallback1, EnHorse_SkinCallback2, 0);
```suggestion
                func_80138258(&this->actor, globalCtx, &this->skin, EnHorse_SkinCallback1, EnHorse_SkinCallback2, false);
```

2022-03-25 19:59 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +                func_80138258(&this->actor, globalCtx, &this->skin, EnHorse_SkinCallback1, EnHorse_SkinCallback2, 1);
```suggestion
                func_80138258(&this->actor, globalCtx, &this->skin, EnHorse_SkinCallback1, EnHorse_SkinCallback2, true);
```

2022-03-25 19:59 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +void EnHorse_SkinCallback1(Actor* thisx, GlobalContext* globalCtx, Skin* skin) {
```suggestion
void EnHorse_PostDraw(Actor* thisx, GlobalContext* globalCtx, Skin* skin) {
```

2022-03-25 19:59 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Horse/z_en_horse.c
> +s32 EnHorse_SkinCallback2(Actor* thisx, GlobalContext* globalCtx, s32 limbIndex, Skin* skin) {
```suggestion
s32 EnHorse_OverrideLimbDraw(Actor* thisx, GlobalContext* globalCtx, s32 limbIndex, Skin* skin) {
```

2022-03-26 03:07 UTC, hensldm approved these changes

2022-03-26 03:25 UTC, AngheloAlf approved these changes

2022-03-29 21:15 UTC, merged