pfsfilestate OK
zeldaret/mm pull request #422
Opened 2021-11-06 11:12 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

I wrote the `if ((ret = ...) != 0)`s as
```c
ret = ...;
if (ret != 0)
```
because I think it's clearer.

2021-11-06 13:58 UTC, Thar0 requested changes

2021-11-06 13:58 UTC, Thar0 commented on src/libultra/io/pfsfilestate.c
> +        ret = __osPfsSelectBank(pfs, 0);
```suggestion
        ret = __osPfsSelectBank(pfs, PFS_ID_BANK_256K);
```

2021-11-06 15:12 UTC, Thar0 approved these changes

2021-11-07 17:20 UTC, kyleburnette approved these changes

2021-11-11 03:58 UTC, Kenix3 approved these changes

2021-11-11 17:16 UTC, merged