pfsdeletefile OK
zeldaret/mm pull request #424
Opened 2021-11-06 11:14 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

As with #422 and #423 , rewrote the ifs to separate the assignments.

2021-11-06 13:59 UTC, Thar0 requested changes

2021-11-06 13:59 UTC, Thar0 commented on src/libultra/io/pfsdeletefile.c
> +        ret = __osPfsSelectBank(pfs, 0);
```suggestion
        ret = __osPfsSelectBank(pfs, PFS_ID_BANK_256K);
```

2021-11-06 15:13 UTC, Thar0 approved these changes

2021-11-07 17:20 UTC, kyleburnette approved these changes

2021-11-08 17:07 UTC, AngheloAlf approved these changes

2021-11-11 03:57 UTC, Kenix3 approved these changes

2021-11-11 16:42 UTC, merged