pfsinitpak OK
zeldaret/mm pull request #425
Opened 2021-11-06 12:00 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2021-11-06 14:07 UTC, Thar0 requested changes

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    ret = __osPfsSelectBank(pfs, 0);
```suggestion
    ret = __osPfsSelectBank(pfs, PFS_ID_BANK_256K);
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +        return (ret);
```suggestion
        return ret;
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    if ((id->deviceid & 0x01) == 0) {
Based on how this is assigned in `__osRepairPackId` I think this makes sense
```suggestion
    if (!(id->deviceid & 1)) {
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +        if ((id->deviceid & 0x01) == 0) {
```suggestion
        if (!(id->deviceid & 1)) {
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    u8 temp[BLOCKSIZE];
Needs updating elsewhere too
```suggestion
    u8 buf[BLOCKSIZE];
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    ret = __osContRamRead(pfs->queue, pfs->channel, 0, saveReg);
```suggestion
    ret = __osContRamRead(pfs->queue, pfs->channel, PFS_ID_0AREA, saveReg);
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    ret = __osContRamWrite(pfs->queue, pfs->channel, 0, temp1, 0);
```suggestion
    ret = __osContRamWrite(pfs->queue, pfs->channel, PFS_ID_0AREA, temp1, 0);
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    ret = __osContRamRead(pfs->queue, pfs->channel, 0, temp2);
```suggestion
    ret = __osContRamRead(pfs->queue, pfs->channel, PFS_ID_0AREA, temp2);
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    return __osContRamWrite(pfs->queue, pfs->channel, 0, saveReg, 0);
```suggestion
    return __osContRamWrite(pfs->queue, pfs->channel, PFS_ID_0AREA, saveReg, 0);
```

2021-11-06 14:07 UTC, Thar0 commented on src/libultra/io/pfsinitpak.c
> +    u8 temp2[BLOCKSIZE];
```suggestion
    u8 writeBuf[BLOCKSIZE];
    u8 readBuf[BLOCKSIZE];
```

2021-11-06 18:16 UTC, Thar0 approved these changes

2021-11-07 17:19 UTC, kyleburnette approved these changes

2021-11-08 17:05 UTC, AngheloAlf approved these changes

2021-11-11 03:57 UTC, Kenix3 approved these changes

2021-11-11 23:24 UTC, merged