pfschecker OK
zeldaret/mm pull request #429
Opened 2021-11-06 15:32 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

Also did some cleanup of contpfs.

... so what is a pfs anyway?

2021-11-06 15:50 UTC, Thar0 requested changes
"Pak File System"

2021-11-06 15:50 UTC, Thar0 commented on src/libultra/io/pfschecker.c
> +                val = nextNodeInFile[j].inode_t.page;
```suggestion
                u8 val = nextNodeInFile[j].inode_t.page;

```

2021-11-06 15:55 UTC, EllipticEllipsis commented
As in controller pak or game pak? Or do both use the same?

2021-11-06 15:58 UTC, Thar0 commented
Controller pak. The "game pak" is the cartridge, which has no inherent filesystem. `z_std_dma.c` and `dmadata` implement a kind of filesystem for that.

2021-11-06 18:17 UTC, Thar0 approved these changes

2021-11-07 17:17 UTC, kyleburnette approved these changes

2021-11-08 16:58 UTC, AngheloAlf approved these changes

2021-11-11 03:44 UTC, Kenix3 approved these changes

2021-11-11 15:29 UTC, merged