pfsisplug OK
zeldaret/mm pull request #430
Opened 2021-11-06 15:46 UTC by EllipticEllipsis

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

This one has some variable renames. That should be it for all the pfs stuff, I think.

2021-11-06 15:53 UTC, Thar0 requested changes

2021-11-06 15:53 UTC, Thar0 commented on src/libultra/io/pfsisplug.c
> +        if ((contData[channel].errno == 0) && ((contData[channel].status & CONT_CARD_ON) != 0)) {
```suggestion
        if ((contData[channel].errno == 0) && (contData[channel].status & CONT_CARD_ON)) {
```

2021-11-06 15:53 UTC, Thar0 commented on src/libultra/io/pfsisplug.c
> +            if ((contData[channel].status & CONT_ADDR_CRC_ER) == 0) {
```suggestion
            if (!(contData[channel].status & CONT_ADDR_CRC_ER)) {
```

2021-11-06 18:17 UTC, Thar0 approved these changes

2021-11-07 17:16 UTC, kyleburnette approved these changes

2021-11-08 16:42 UTC, AngheloAlf approved these changes

2021-11-08 16:42 UTC, AngheloAlf commented on src/libultra/io/contsetch.c
> +    __osContLastPoll = -2;
This is a bit out of scope, but it looks like there are some macros in controller.h for this magic numbers.
We should make a clean up PR for stuff like this in the future

2021-11-11 03:43 UTC, Kenix3 approved these changes

2021-11-11 03:43 UTC, merged