Importing Audio Init Params
zeldaret/mm pull request #471
Opened 2021-11-19 23:00 UTC by engineer124

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

This imports initialization parameters used by Audio Heap while initializing audio. This file is similar to OoTs:
https://github.com/zeldaret/oot/blob/master/src/code/audio_init_params.c

For direct comparison:
- heapSize: MM 0x137F00 <--> 0x37F00 OoT
- initPoolSize: MM 0x1C480 <--> 0xE0E0 OoT
- permanentPoolSize: MM 0x1A000 <--> 0xBCE0 OoT

(gTatumsPerBeat is identical between the two games).

So in other words, audio heap in MM got leveled up.

2021-11-20 00:34 UTC, isghj5 commented
`For direct comparison:

    heapSize: MM 0x137F00 <--> 0x37F00 OoT
    initPoolSize: MM 0x1C480 <--> 0xE0E0 OoT
    permanentPoolSize: MM 0x1A000 <--> 0xBCE0 OoT
`
Cool, although if this was me I would add these three var names next to their data on line audio_init_parms::8

2021-11-20 02:21 UTC, isghj5 approved these changes

2021-11-20 15:49 UTC, AngheloAlf approved these changes
Just a small nitpick, but I'll approve anyways in the meanwhile

2021-11-20 15:49 UTC, AngheloAlf commented on tools/disasm/variables.txt
> +    0x801E1100:("D_801E1100","UNK_TYPE4","",0x4),
```suggestion
    0x801E1100:("D_801E1100","s16","",0x4),
```

2021-12-06 16:56 UTC, EllipticEllipsis approved these changes

2021-12-06 20:17 UTC, Kenix3 requested changes

2021-12-06 20:17 UTC, Kenix3 commented on src/code/audio/audio_init_params.c
> +const s16 D_801E1100[] = {
```suggestion
const s16 gAudioTatumInit[] = {
```
maybe?

2021-12-06 20:17 UTC, Kenix3 commented on src/code/audio/audio_init_params.c
> +const AudioContextInitSizes D_801E1104 = {
```suggestion
const AudioContextInitSizes gAudioContextInitSizes = {
```

2021-12-16 23:59 UTC, Kenix3 approved these changes

2021-12-19 20:01 UTC, merged