z_bg_goron_oyu OK
zeldaret/mm pull request #487
Opened 2021-11-29 17:33 UTC by mzxrules

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---
Supersedes pr #206

2021-11-29 17:40 UTC, AngheloAlf commented on src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c
> +    CollisionHeader* waterBox;
Emmm, what?

2021-11-29 17:40 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Goron_Oyu/z_bg_goron_oyu.c
> -
We haven't decided what we are going to do with the `THIS`macro, so I suggest to bring it back and use it where appropriate

2021-11-29 17:40 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Goron_Oyu/z_bg_goron_oyu.c
> +    Math_StepToF(&this->unk_164, 0.0f, 0.2f);
Please add an empty line between the variables declarations and the actual code
```suggestion
    static Vec3f D_80B40780 = { 0, 0, 0 };

    Math_StepToF(&this->unk_164, 0.0f, 0.2f);
```

2021-11-30 00:42 UTC, m4xw approved these changes
looks generally good to me

2021-12-01 03:24 UTC, AngheloAlf approved these changes

2021-12-04 04:14 UTC, EllipticEllipsis approved these changes
One minor thing, but I'll not let it stand in the way of approval.

2021-12-04 04:14 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Bg_Goron_Oyu/z_bg_goron_oyu.c
> +    s32 pad;
```suggestion
    BgGoronOyu* this = THIS;
    s32 pad;
```
If this is a GlobalContext upcast pad, it tends to go above the Actor recast.

2021-12-06 20:26 UTC, Kenix3 requested changes

2021-12-06 20:26 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Goron_Oyu/z_bg_goron_oyu.h
> +    /* 0x160 */ u8 unk_160[4];
```suggestion
    /* 0x160 */ UNK_TYPE1 unk_160[4];
```

2021-12-16 04:10 UTC, Kenix3 approved these changes

2021-12-19 19:20 UTC, merged