ovl_Obj_Kzsaku OK
zeldaret/mm pull request #506
Opened 2021-12-08 09:42 UTC by shawlucas

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

ok

2021-12-20 04:29 UTC, EllipticEllipsis reviewed
A few things. I think it would be quite easy to complete the documentation on this actor, though, would recommend you do so.

2021-12-20 04:29 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.c
> +    s32 pad;
```suggestion
    s32 pad;
    ObjKzsaku* this = THIS;
```
Does this match? Usually it's this way when required.

2021-12-20 04:29 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.c
> +    Actor_SetScale(thisx, 1.0f);
Required to match? Remember to use `&this->dyna.actor` if not.

2021-12-20 04:29 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.c
> +        this->timer++;
I'd prefer an else, I think, since these are on a pretty equal footing.

2021-12-20 04:29 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.h
> +    /* 0x016A */ s16 unk_16A;
This seems to just be struct padding.
```suggestion
```

2021-12-20 04:29 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.h
> +    /* 0x0160 */ f32 unk_160;
The way this is used suggests it's the amount the grate has raised.

2021-12-20 18:12 UTC, hensldm approved these changes
LGTM

2021-12-25 01:47 UTC, shawlucas commented
I would do documentation, but I'm really bad at coming up with names for stuff. I understand what most of the functions do but actually naming them is hard for me lol

func_80C08B60: Sets the grate position to the initial position and sets the action function to a function that checks if the switch flag is set.

func_80C08B7C: Checks if the switch flag is set, if it is, call func_80C08BBC.

func_80C08BBC: Sets action function to func_80C08BD0.

func_80C08BD0: Plays the grate opening cutscene (I think) if cutscene != -1. Raises the grate to the correct amount. If the grate is at the correct amount, call func_80C08C84.

2021-12-27 21:35 UTC, hensldm reviewed
Possible Naming suggestions:
`func_80C08B60`: Seems to be setting up `func_80C08B7C`, so perhaps SetupIdle
`func_80C08B7C`: Looks like the idle function while it waits for the switch to be hit, so perhaps Idle
`func_80C08BBC`: Sets up func_80C08BD0, so perhaps SetupRise
`func_80C08BD0`: Looks like it is what causes the grate to rise, so perhaps Rise
`func_80C08C84`: Sets up func_80C08C84, so perhaps SetupWaitForCutscene
`func_80C08CB0`: Just waits to stop the cutscene, so perhaps WaitForCutscene

Admittedly I'm not sure on `func_80C08CB0` and `func_80C08C84`, but can't think of anything better.
Also don't be afraid to ask for possible name suggestions in the discord.

2021-12-27 21:35 UTC, hensldm commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.c
> +    CollisionHeader_GetVirtual(&D_06001118, &col);
With objects now in, you should be able to include the relevant object header and use the correct symbol.

2021-12-27 21:35 UTC, hensldm commented on src/overlays/actors/ovl_Obj_Kzsaku/z_obj_kzsaku.c
> +    gSPDisplayList(POLY_OPA_DISP++, D_06000040);
Same here

2021-12-27 21:38 UTC, hensldm requested changes
Up to you on the function names, but would like to see the object included properly before approval.

2022-01-03 21:17 UTC, shawlucas commented
renamed some functions and added the object

2022-01-05 22:31 UTC, hensldm approved these changes

2022-01-15 21:34 UTC, AngheloAlf approved these changes

2022-01-16 14:39 UTC, Kenix3 approved these changes

2022-01-23 12:40 UTC, merged