Obj_Flowerpot
zeldaret/mm pull request #539
Opened 2021-12-27 16:30 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2021-12-27 16:49 UTC, AngheloAlf requested changes

2021-12-27 16:49 UTC, AngheloAlf commented on src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
> +    s32 sp28 = this->collider.elements[0].info.toucherFlags & 2;
```suggestion
    s32 sp28 = this->collider.elements[0].info.toucherFlags & TOUCH_HIT;
```

2021-12-27 16:49 UTC, AngheloAlf commented on src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
> +        this->collider.elements[0].info.toucherFlags &= ~1;
```suggestion
        this->collider.elements[0].info.toucherFlags &= ~TOUCH_ON;
```

2021-12-27 19:45 UTC, AngheloAlf approved these changes

2021-12-27 23:33 UTC, hensldm approved these changes

2022-01-04 01:00 UTC, Kenix3 approved these changes

2022-01-04 06:37 UTC, merged