En_Vm
zeldaret/mm pull request #678
Opened 2022-02-18 22:40 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2022-02-19 01:10 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +        if (this->unk_214 < 301) {
```suggestion
        if (this->unk_214 <= 300) {
```
probably will make more sense.

2022-02-19 01:10 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +        sp50.x = (Math_CosS(this->actor.shape.rot.y + this->unk_218) * 5.0f) + this->unk_234.x;
Can this addition go the other way round to match the z one?

2022-02-27 23:18 UTC, hensldm approved these changes

2022-02-27 23:18 UTC, hensldm commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, 1.0f, lastFrame, lastFrame, 2, 0.0f);
```suggestion
    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, 1.0f, lastFrame, lastFrame, ANIMMODE_ONCE, 0.0f);
```

2022-02-27 23:18 UTC, hensldm commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, 3.0f, 3.0f, 7.0f, 2, 0.0f);
```suggestion
    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, 3.0f, 3.0f, 7.0f, ANIMMODE_ONCE, 0.0f);
```

2022-02-27 23:18 UTC, hensldm commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +                     0.0f, 2, 0.0f);
```suggestion
    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, -1.0f, Animation_GetLastFrame(&object_vm_Anim_000068),
                     0.0f, ANIMMODE_ONCE, 0.0f);
```

2022-02-27 23:18 UTC, hensldm commented on src/overlays/actors/ovl_En_Vm/z_en_vm.c
> +                     0.0f, 2, 0.0f);
```suggestion
    Animation_Change(&this->skelAnime, &object_vm_Anim_000068, -1.0f, Animation_GetLastFrame(&object_vm_Anim_000068),
                     0.0f, ANIMMODE_ONCE, 0.0f);
```

2022-02-27 23:19 UTC, EllipticEllipsis approved these changes

2022-03-05 00:39 UTC, Kenix3 requested changes
See @hensldm's suggestions

2022-03-23 23:26 UTC, Kenix3 approved these changes

2022-03-25 01:55 UTC, merged