Bg_Spdweb (1 non-matching)
zeldaret/mm pull request #685
Opened 2022-02-21 05:08 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

func_809CE830: https://decomp.me/scratch/9ELQw - might help to look at func_809CE234 in the context or PR, same type of func.

2022-02-21 14:55 UTC, AngheloAlf approved these changes

2022-02-21 16:03 UTC, jpburnett approved these changes
Comments are just on seeing if the floats could be represented differently.  Great work overall🕸️

2022-02-21 16:03 UTC, jpburnett commented on src/overlays/actors/ovl_Bg_Spdweb/z_bg_spdweb.c
> +            temp_f28 = Math_Vec3f_DistXYZ(&this->dyna.actor.home.pos, &spD0) * 0.011111111f;
Would (1.0f / 90.0f) work?

2022-03-05 00:41 UTC, Kenix3 requested changes
Please see @jpburnett's comments

2022-03-24 04:01 UTC, Kenix3 approved these changes

2022-03-25 02:30 UTC, merged