Bg_Kin2_Shelf
zeldaret/mm pull request #759
Opened 2022-03-26 03:49 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2022-03-26 05:21 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    s32 temp_v1 = (D_80B70778[params] & this->unk_164) & 0xFF;
Maybe temp_v1 is a u8?

2022-03-26 05:21 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        return (this->unk_167 < 0) ^ 1;
This doesn't match with an `>=` or a `!(this->unk_167 < 0)`?

2022-03-26 05:21 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        return (this->unk_166 < 0) ^ 1;
Same

2022-03-26 06:10 UTC, hensldm approved these changes

2022-03-27 17:26 UTC, AngheloAlf approved these changes

2022-03-29 01:54 UTC, Kenix3 requested changes

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & (0x8 | 0x2)) {
```suggestion
    if (this->unk_164 & ((1 << 3) | (1 << 1))) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 1) {
```suggestion
    if (this->unk_164 & (1 << 0)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 2) {
```suggestion
    if (this->unk_164 & (1 << 1)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        return temp_v1 & (0x8 | 0x2);
```suggestion
        return temp_v1 & ((1 << 3) | (1 << 1));
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        return false;
```suggestion
        return 0;
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    return temp_v1 & 5;
```suggestion
    return temp_v1 & ((1 << 2) | (1 << 0));
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 1) {
```suggestion
    if (this->unk_164 & (1 << 0)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +            if (this->unk_164 & (0x8 | 0x2)) {
```suggestion
            if (this->unk_164 & ((1 << 3) | (1 << 1))) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        if (this->unk_164 & 8) {
```suggestion
        if (this->unk_164 & (1 << 3)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        if (this->unk_164 & 8) {
```suggestion
        if (this->unk_164 & (1 << 3)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        if (this->unk_164 & 4) {
```suggestion
        if (this->unk_164 & (1 << 2)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +        if (this->unk_164 & 4) {
```suggestion
        if (this->unk_164 & (1 << 2)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 2) {
```suggestion
    if (this->unk_164 & (1 << 1)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 4) {
```suggestion
    if (this->unk_164 & (1 << 2)) {
```

2022-03-29 01:54 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
> +    if (this->unk_164 & 8) {
```suggestion
    if (this->unk_164 & (1 << 3)) {
```

2022-04-17 15:08 UTC, Kenix3 approved these changes

2022-04-17 17:39 UTC, merged