Bg_Ikana_Block
zeldaret/mm pull request #761
Opened 2022-03-26 05:12 UTC by Kelebek1

Before opening this PR, ensure the following:
- `./format.sh` was run to apply standard formatting.
- `make` successfully builds a matching ROM.
- No new compiler warnings were introduced during the build process.
    - Can be verified locally by running `tools/warnings_count/check_new_warnings.sh`
- New variables & functions should follow standard naming conventions.
- Comments and variables have correct spelling.
---

2022-03-26 05:30 UTC, AngheloAlf approved these changes

2022-03-26 06:07 UTC, hensldm approved these changes

2022-03-29 02:04 UTC, Kenix3 requested changes

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    if (this->unk_17A & (0x2 | 0x1)) {
```suggestion
    if (this->unk_17A & ((1 << 1) | (1 << 0))) {
```

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    if (this->unk_17A & (0x4 | 0x1)) {
```suggestion
    if (this->unk_17A & ((1 << 2) | (1 << 0))) {
```

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    this->unk_17C &= ~7;
```suggestion
    this->unk_17C &= ~((1 << 2) | (1 << 1) | (1 << 0));
```

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    this->unk_17C |= 2;
```suggestion
    this->unk_17C |= (1 << 1);
```

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    this->unk_17C &= ~7;
```suggestion
    this->unk_17C &= ~((1 << 2) | (1 << 1) | (1 << 0));
```

2022-03-29 02:04 UTC, Kenix3 commented on src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
> +    this->unk_17C |= 4;
```suggestion
    this->unk_17C |= (1 << 2);
```

2022-04-17 15:36 UTC, Kenix3 approved these changes

2022-04-17 19:06 UTC, merged