z_en_item00
zeldaret/mm pull request #78
Opened 2021-03-22 05:08 UTC by Rozelette

17/21 functions OK, with the others pretty close to it, but as I have not been making headway with them I am PRing it. I added a decent amount of documentation formatted the same way as OOT. I could not find a definitive source of info for MM's item IDs, so I only filled in what I could absolutely determine. I also threw in a quick way to split rodata for code files, but I didn't test it out extensively.

2021-03-22 22:00 UTC, Kenix3 requested changes
Looks good to me. Just have a few naming issues.

Also, looks like you have a merge conflict. Please update your PR to rebase on master. Thank you for the submission!

2021-03-22 22:14 UTC, Rozelette commented on include/macros.h
> +#define LINK_IS_CHILD (gSaveContext.perm.linkAge != 0)
I think it's just a remnant from OOT. As far as I can tell looking at it in Ghidra, it is never set to anything other than 0. However, it is checked at various places in the code. It is also still called `link_age` internally. Would you prefer these macros and the variable rename to `unk7`?

2021-03-22 22:15 UTC, Rozelette commented on src/code/z_en_item00.c
> +u8 sDropTableAmounts[16 * 17] = {
17 drop tables of 16 entries each. I was somewhat unsure making them a macro but I'll do so

2021-03-27 17:52 UTC, Kenix3 approved these changes
We decided to go ahead and keep linkAge, since it's not used, and it's in MM debug screen strings.
Ready to merge as soon as conflicts are resolved.

2021-03-28 00:55 UTC, merged