ovl_En_Gamelupy decompiled
zeldaret/mm pull request #878
Opened 2022-06-27 07:39 UTC by sonicdcer

2022-06-28 05:12 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.h
> +    /* 0x198 */ s16* unk_198;
My guess is that this is actually an Actor*, but we should probably wait for more info from `EnLookNuts`. Can you add a `//! TODO: Look at type based on EnLookNuts decomp`?

2022-06-28 14:41 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +};
I feel like we've been here before... this will need updating once the other PR that touches these goes in.

2022-06-28 14:41 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    this->actor.shape.rot.y += 500;
Angle, so in hex.

2022-06-28 14:41 UTC, EllipticEllipsis commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    Actor_UpdateBgCheckInfo(play, &this->actor, 32.0f, 30.0f, 0.0f, 12);
Last variable is flags, should be hex.

2022-06-28 23:16 UTC, hensldm approved these changes

2022-06-28 23:16 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +static Color_RGBA8 envColor = { 100, 200, 0, 255 };
```suggestion
static Color_RGBA8 sPrimColor = { 255, 255, 255, 255 };

static Color_RGBA8 sEnvColor = { 100, 200, 0, 255 };
```

2022-07-02 15:33 UTC, hensldm requested changes
Some thoughts now that we have more info from `EnLiftNuts`.

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.h
> +    /* 0x198 */ s16* unk_198; //! TODO: Look at type based on EnLookNuts decomp
```suggestion
    /* 0x198 */ s16* unk_198;
```
So looking at the EnLookNuts PR, this is in fact an `s16*`, so the todo is no longer needed.

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    if ((this->collider.base.ocFlags1 & OC1_HIT)) {
```suggestion
    if (this->collider.base.ocFlags1 & OC1_HIT) {
```

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +        *temp_v0 += 0x32;
```suggestion
        *this->unk_198 += 0x32;
```
Is the temp necessary?

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    void* actor = func_800B6680(play, ACTOR_EN_GAMELUPY);
```suggestion
    s16* unk_198 = func_800B6680(play, ACTOR_EN_GAMELUPY);
```
Now that we know that `this->unk_198` is in fact an `s16*`, we can give the proper type. Also `actor` no longer seems like a reasonable name, so `unk_198` seems fine for the meantime.

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    Actor_UpdateBgCheckInfo(play, &this->actor, 32.0f, 30.0f, 0.0f, 0x0C);
```suggestion
    Actor_UpdateBgCheckInfo(play, &this->actor, 32.0f, 30.0f, 0.0f, 0xC);
```

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    this->actor.shape.rot.y += 1000;
```suggestion
    this->actor.shape.rot.y += 0x3E8;
```
Rotation so should be in hex for now.

2022-07-02 15:33 UTC, hensldm commented on src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
> +    if (this->unk_19C >= 0x1F) {
```suggestion
    if (this->unk_19C > 30) {
```
`unk_19C` seems better in decimal

2022-07-03 16:44 UTC, hensldm approved these changes

2022-07-05 01:29 UTC, EllipticEllipsis approved these changes

2022-07-11 23:05 UTC, Kenix3 approved these changes

2022-07-12 01:56 UTC, merged