dm_sa OK
zeldaret/mm pull request #88
Opened 2021-03-27 09:45 UTC by kyleburnette

2021-03-27 17:48 UTC, Kenix3 requested changes
Looks good to me, one small nitpick.

2021-03-27 17:48 UTC, Kenix3 commented on src/overlays/actors/ovl_Dm_Sa/z_dm_sa.h
> +    /* 0x188 */ char unk194[0x108];
I generally like to keep these unk fields UNK_TYPE1 if it still matches, to signal to the reader of this code that we don't know the signedness of this data.

2021-03-27 18:53 UTC, Rozelette requested changes
LGTM except for nits and the extraneous files

2021-03-27 18:53 UTC, Rozelette commented on ctx.c
> +typedef signed char s8;
This file shouldn't be included

2021-03-27 18:53 UTC, Rozelette commented on src/overlays/actors/ovl_Dm_Sa/z_dm_sa.c
> +        frameCount = (f32)SkelAnime_GetFrameCount(animations->animation);
Is this cast needed?

2021-03-27 18:53 UTC, Rozelette commented on src/overlays/actors/ovl_Dm_Sa/z_dm_sa.c
> +    dList = dListHead = GRAPH_ALLOC(gfxCtx, sizeof(Gfx) * 2);
I saw the discussion about this bug, so I'd put
```suggestion
    dList = dListHead = GRAPH_ALLOC(gfxCtx, sizeof(Gfx) * 2); //! @bug this does not allocate enough for 3 Gfx commands
```

2021-03-27 18:53 UTC, Rozelette commented on tools/gen_mips_to_c_context.py:Zone.Identifier
> +[ZoneTransfer]
Remove this file

2021-03-27 19:23 UTC, Rozelette approved these changes
LGTM

2021-04-07 21:21 UTC, Kenix3 approved these changes
Looks good to me.

2021-04-07 22:08 UTC, merged