Match and Document code_80172BC0.c
zeldaret/mm pull request #909
Opened 2022-07-06 20:46 UTC by engineer124

2022-07-06 20:48 UTC, EllipticEllipsis approved these changes

2022-07-06 21:03 UTC, hensldm approved these changes
Interesting fake match

2022-07-06 23:31 UTC, hensldm requested changes

2022-07-06 23:31 UTC, hensldm commented on src/code/code_80172BC0.c
> +    for (bankIdPtr = sSfxBankIds; bankIdPtr < (sSfxBankIds + sizeof(sSfxBankIds)); bankIdPtr++) {
```suggestion
    for (bankIdPtr = sSfxBankIds; bankIdPtr < (sSfxBankIds + ARRAY_COUNT(sSfxBankIds)); bankIdPtr++) {
```
Just so we don't forget, and as mentioned in the OoT Pr.

2022-07-07 00:28 UTC, hensldm approved these changes

2022-07-09 16:31 UTC, jpburnett approved these changes

2022-07-11 23:20 UTC, Kenix3 approved these changes

2022-07-12 03:14 UTC, merged